[package]
name = "my_x11_hotkeys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
enigo = "0.5.0"
global-hotkey = "0.7.0"
